### ISSUE TITLE
The Theme's Demo on the Hugo Website is missing its Hugo Pipes Assets

### ISSUE THREAD

**Issue by onedrawingperday** [vickylai/hugo-theme-introduction#106]
Hi @vickylai 

On the Hugo Themes website the [demo](https://themes.gohugo.io/theme/hugo-theme-introduction/) of the [Hugo Theme Introduction](https://themes.gohugo.io/hugo-theme-introduction/) has its Hugo Pipes Assets missing. 

To fix this issue please see the [Common Permalink Issues](https://github.com/gohugoio/hugoThemes#common-permalink-issues) in the updated README of the Hugo Themes repository.

>If you are using Hugo Pipes to publish your theme's resources you need to use `.RelPermalink` in the templates, so that these assets are served correctly on the website.

For example change line 11 of `/layouts/partials/base/imports.html/` to:
`<link rel="stylesheet" href="{{ $bundle.RelPermalink }}" integrity="{{ $bundle.Data.Integrity }}" media="screen">`

and line 17 to:
`<link rel="stylesheet" href="{{ $style.RelPermalink }}" integrity="{{ $style.Data.Integrity }}" media="screen">`

You need to do this change for every Hugo Pipes Asset that is used in your theme's templates.

Please do this change and let me know.

Thanks!

CC / @digitalcraftsman

**Comment by hanzei** [comment]
Hi @onedrawingperday,
Thanks for the heads up! I will fix this.

Just wondering: Why is it needed to use `.RelPermalink`?

**Comment by hanzei** [comment]
> Because if one uses `.Permalink` for Hugo Pipes resources then these will get the wrong URL and will be missing from the theme's demo on the Hugo website.

Sure, I get this. But why does the wrong URL gets generated?

**Comment by onedrawingperday** [comment]
>Sure, I get this. But why does the wrong URL gets generated?

A theme's demo site lives in a sub-directory. Typically in every instance we advice theme authors to use the `absURL` function or `.Permalink` to create absolute URLs in the templates.

Why this is the opposite with Hugo Pipes Assets? Why does one have to use .RelPermalink in the templates, so that these assets are served correctly on the Themes website?

Well @hanzei this is a question that only @bep can answer.

CC / @digitalcraftsman

**Comment by hanzei** [comment]
Just a short addition to my previous post:
https://themes.gohugo.io is **the** website to show hugo themes. If themes can't use `.Permalink` for assets, this is a drawback. Because of this I why this problem occurs.

**Comment by bep** [comment]
>Because if one uses .Permalink for Hugo Pipes resources then these will get the wrong URL a

I assume there is a GitHub issue describing this bug?

**Comment by onedrawingperday** [comment]
>I assume there is a GitHub issue describing this bug?

@bep None that I am aware of. I did inform you though when I first discovered that `.RelPermalink` is needed for Hugo Pipes Assets in demos over [here](https://github.com/gohugoio/hugoThemes/issues/395#issuecomment-409029194)

I didn't get a reply so I assumed that this was as-is-behavior.

Also we have added it in the repository's README over [here](https://github.com/gohugoio/hugoThemes#common-permalink-issues)

If this is indeed a bug I hope that it's resolution won't break every theme that uses Hugo Pipes.

**Comment by bep** [comment]
It's reported here:

https://github.com/gohugoio/hugo/issues/5226

**Comment by onedrawingperday** [comment]
>(.RelPermalink and .Permalink should behave the same vs any path in baseURL (there are more to this story, but that's not relevant for this particular issue))
They don't behave the same on the Hugo Themes website. `RelPermalink` , `RelURL` and URLs that start with a forward slash `/` are always made relative to the root of website. Theme Demos live in sub-directories. Therefore if these relative URLs are used for theme assets they will end up missing because they will be created relative to `themes.gohugo.io` and not `themes.gohugo.io/some-theme/`.

>That is has taken some time to fix this issue isn't a reason not to fix it, is it? It's not like we have full staff of Hugo devs doing 24/7 bug fixing?
The answers to these questions go without saying and I didn't say anything of this sort in my comment above. 

What I did say is that you were informed well in advance and since then we have been instructing lots of people to construct their Hugo Pipes Assets URLs a certain way to get them served on Themes Website.

---

Anyway @hanzei given the new insight we have all gained here tonight, if you want the Introduction Theme's CSS to load on the Hugo Themes website as things are right now you need to follow my advice from above. Of course that might become the opposite in the future but until then that's how it is.

**Comment by hanzei** [comment]
@onedrawingperday I'v submitted a PR to fix this.

@onedrawingperday @bep Thank you very much for the time and effort you guys put into Hugo!

**Comment by hanzei** [comment]
Since https://github.com/gohugoio/hugo/issues/5226 is fixed, is there any need for changes in this theme?

**Comment by onedrawingperday** [comment]
@hanzei nothing really changed regarding the guidance I gave.

So the PR you sent to fix this theme should be merged.
