### ISSUE TITLE
Fonts missing from the Theme's Demo on the Hugo website

### ISSUE THREAD

**Issue by onedrawingperday** [vickylai/hugo-theme-introduction#109]
Hello @hanzei for the Fontawesome icons and the Nunito Sans fonts to load in your theme's demo on the Hugo website, you need to change [lines 2-3](https://github.com/vickylai/hugo-theme-introduction/blob/master/assets/sass/style.sass#L2-L3) of `/hugo-theme-introduction/assets/sass/style.sass`] to the following:

```
$fa-font-path: {{ "fonts/fontawesome-free/webfonts" | absURL }}
$nunito-font-path: {{ "fonts/NunitoSans" | absURL }}
```

For an explanation of these changes please have a look at the [Common Permalinks Issues](https://github.com/gohugoio/hugoThemes#common-permalink-issues) in the README of the Hugo Themes repository.

Also I tested the theme demo with the Build Script without regenerating the theme's resources and the fonts don't seem to load even after making the above changes. So I suppose that in this case it is needed to regenerate.

Thanks.

**Comment by hanzei** [comment]
You can't use absolute URLs in css font-face src paths as far as I know.

The changes you propose produce an error because of this:
```bash
$ hugo --themesDir ../.. 
Building sites … ERROR 2018/11/28 18:44:22 error: failed to transform resource: SCSS processing failed: file "stdin", line 2, col 16: Invalid CSS after "...font-path: http": expected 1 selector or at-rule, was ":;//example.com/fon" 
Total in 117 ms
Error: Error building site: logged 1 error(s)

```

**Comment by hanzei** [comment]
Hugo 0.52 should fix this, right? Could you update https://github.com/gohugoio/hugoThemes to Hugo 0.52 and see if it works?

**Comment by onedrawingperday** [comment]
@hanzei 

Locally I am on Hugo 0.53 DEV extended. So this issue has nothing to do with Hugo 0.52

I have just reproduced the above ERROR you mentioned. Sorry I should have tested more before opening this issue.

From what I gather that you store the full webfont PATH in those variables hence the ERROR with the above changes.

The [Hugo Bilberry Theme](https://github.com/Lednerb/bilberry-hugo-theme) had the same problem with its Icon fonts and the above snippet fixed the problem. 

But the author of that theme did not store the entire PATH of the webfont (like you are doing in this theme) but only [the folder in which the webfonts are located](https://github.com/Lednerb/bilberry-hugo-theme/blob/master/assets/sass/_variables.scss#L1-L2) and then used this variable like [this](https://github.com/Lednerb/bilberry-hugo-theme/blob/3ef30975bf12b287ee922034b74d5928e1a74a90/assets/sass/fontface.scss) in the `fontface.scss` stylesheet:

```
@font-face {
  font-family: 'flexslider-icon';
  src: url($fonts-folder + 'flexslider-icon.eot');
  src: url($fonts-folder + 'flexslider-icon.eot?#iefix') format('embedded-opentype'), url($fonts-folder + 'flexslider-icon.woff') format('woff'), url($fonts-folder + 'flexslider-icon.ttf') format('truetype'), url($fonts-folder + 'flexslider-icon.svg#flexslider-icon') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
In any case the best way to view the problem I am reporting about the missing Fontawesome and Nunito fonts on your own is to clone the Hugo Themes Repo locally and test your theme with the Build Script as instructed in the [README](https://github.com/gohugoio/hugoThemes#testing-a-theme-with-the-hugo-themes-website-build-script)

i think that you need to rethink the values that are stored in those variables.

However I'm sorry but I don't have the time to look into this further.

**Comment by hanzei** [comment]
Thank you very much for your help @onedrawingperday! I was able to fix the problem. Could you please pull the current `master` of this theme and test it?

**Comment by onedrawingperday** [comment]
@hanzei Right. So the fix in https://github.com/vickylai/hugo-theme-introduction/commit/5895d84506e343b20d34d76c51edcc879602d666 was much simpler after all.

Now everything is looking good on my end when I execute the Build Script. 👍 

The Introduction Theme's demo will be fixed on the Hugo website the next time that @digitalcraftsman updates the themes.
