### ISSUE TITLE
Add Mastodon website verification setting

### ISSUE THREAD

**Issue by SaschaMann** [vickylai/hugo-theme-introduction#121]
Mastodon allows users to verify a website linked in their profile is owned by them by adding a link on their website that contains a `rel="me"` attribute and links to their mastodon profile, e.g. `<a rel="me" href="https://foo.social/@bar">Mastodon</a>`.

Currently, there is no trivial way to add that attribute to the link by only using the `params.social` part of the `config.toml` file. I realise this is a bit of an edge case, but it would be nice to have an option that allows this.

**Comment by hanzei** [comment]
Hey @SaschaMann,

You are talking about the social icons in the ntroduction and contact section, right?

If you, I don't see an simple way to add such information to `config.toml`. What would be your proposed solution?

**Comment by SaschaMann** [comment]
Yep, that section. I am not quite sure if there's a good way (very limited experience with hugo themes and modern HTML) that isn't mastodon-specific but would work for this. Mostly opened the issue as suggestion/some issue I ran into as a user, without having a decent solution in mind. 

Perhaps an optional `rel` parameter?

```
    [[params.social]]
        url   = "https://foo.social/@bar"
        icon  = "mastodon" # icon name without the 'fa-'
        icon_pack = "fab"
        rel = "me"
```

Or, to keep it a bit more general, an optional parameter that allows arbitrary HTML attributes and inserts them in the generated link?
```
    [[params.social]]
        url   = "https://foo.social/@bar"
        icon  = "mastodon" # icon name without the 'fa-'
        icon_pack = "fab"
        html_attrs = "rel=\"me\" target=\"_blank\""
```

**Comment by hanzei** [comment]
> Or, to keep it a bit more general, an optional parameter that allows arbitrary HTML attributes and inserts them in the generated link?

This would be fine. Would you be open to submit a PR for this? It could be a good place to start with hugo :wink:

**Comment by SaschaMann** [comment]
I'll give it a try!
