### ISSUE TITLE
Compilation Errors - css/main.tmp.css

### ISSUE THREAD

**Issue by glebt** [vickylai/hugo-theme-introduction#123]
Building sites … ERROR 2019/01/06 13:17:49 error: failed to transform resource: TOCSS: failed to transform "css/main.tmp.css" (text/x-sass): this feature is not available in your current Hugo version
Total in 1407 ms
Error: Error building site: logged 1 error(s)

Tried in 0.53 and .52

**Comment by hanzei** [comment]
@glebt Did you use the **extended** version of Hugo? Could you please report your Hugo version? You can show it with `hugo version`.

**Comment by glebt** [comment]
@hanzei 

C:\hugo_sites\my-cool-site>hugo version
Hugo Static Site Generator v0.52 windows/amd64 BuildDate: 2018-11-28T14:07:10Z

not sure if it's extended

**Comment by glebt** [comment]
thanks, that worked. closing it...
