### ISSUE TITLE
CSS not loading on production site

### ISSUE THREAD

**Issue by solrayc** [vickylai/hugo-theme-introduction#134]
Hi, 
My site does not render CSS when on firebase hosting.
Chrome shows this in console:

```
Failed to find a valid digest in the 'integrity' attribute for resource 'https://myprivate-project.firebaseapp.com/css/main.min.ccf09f8a4430995d4fa17756531c4091cf3f771b1c1db86b32c80b0e31b8c31c.css' with computed SHA-256 integrity 'HfWlt2/BRD8jIjukxmLJTtFyWHcyUfg97VBLEtFNQCA='. The resource has been blocked.
```

My site renders just fine in local dev environment with `hugo server`.

Hugo version 

```
Hugo Static Site Generator v0.54.0/extended windows/amd64 BuildDate: unknown
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.11.5"
```

I have set my baseURL to something like this: `https://myprivate-project.firebaseapp.com/`. is, of course not the real url I'm using. 

Love this theme.
Thank you for your help.

**Comment by solrayc** [comment]
Fix it by installing dependencies:
```
autoprefixer: npm install -g autoprefixer
postcss-cli:npm install -g postcss-cli
```

**Comment by hanzei** [comment]
Glad you figured it out yourself :wink:
