### ISSUE TITLE
Multilingual site support

### ISSUE THREAD

**Issue by pmviva** [vickylai/hugo-theme-introduction#14]
Hi Vicky, i really like your theme, nice work! I was wondering if you were planning on adding support for multilingual sites.

As far as I can see, hugo supports translation of strings so it should be easy enough to move all untranslated text in templates to a data file, make sure the templates are using relLangURL, absLangURL and displaying some sort of link to translated content (posts, etc).

If you want I can give you a hand implementing the missing functionality in the theme and submit a pull request.

**Comment by pmviva** [comment]
I've been thinking about the best solution to support multilingual sites. I've noticed that the theme assumes the about page has title "About" and the contact page has tittle "Contact".

For example:
```
{{ range .Data.Pages }}
    {{if eq .Title "Contact" }}
        {{.Content}}
    {{end}}
{{ end }}
```
Would not work  for multilingual sites. For instance in English I would have a page with title "Contact", in Spanish the same page would have title "Contacto".

I was thinking about two possible solutions (besides checking the page language is the same current language used for rendering):
1. Having the title of the about / contact page for each language in a language dependent data file
2. Having a variable in front matter indicating whether or not the page is an about / contact page

I guess the 1st solution is the easiest one.

What do you think?

**Comment by hivickylai** [comment]
The language data file is an interesting concept. My main concern would be to reduce any excessive customization that would need to be done. If the user requires a different language, they can set it, and otherwise the default settings allow English language use without additional barriers or confusion.

It could also work as a params variable from the config file, if the only words that need translation are the references to those two markdown files.

**Comment by pmviva** [comment]
The language data files only hold translation of strings (Menu Links, 404 page message, headers, footer, copyright, post information like read time, etc) and the theme should provide default ones for the languages that wish to support out of the box. So for instance if the theme provides English and Spanish out of the box, the users shouldn't do any extra configuration on the site or the theme besides configuring that they will build a multilingual site in English and Spanish.

The theme user should create a new language data file for the languages that doesn't come out of the box in the theme.

In my pull request I've included both English and Spanish translation and I've modified the example site's config.toml to reflect that you can change a few configurations per language basis but in fact you could have a set of default values and anything not overriden per language will use default values.

**Comment by d6s5** [comment]
Multilingual site support would be great. I like the theme very much but after some time I realized that I couldn't customize the menu and other language related things. So I couldn't use it for german as much as I like it.

**Comment by pmviva** [comment]
@d6s5 I just made a pull request with multilingual support, lets hope @hivickylai reviews it and approves it.

In the meantime you can checkout my fork of the theme, download and play with it in order to find any bugs I missed
