### ISSUE TITLE
Rework theme css to be more organized/not include Bulma

### ISSUE THREAD

**Issue by vickylai** [vickylai/hugo-theme-introduction#29]
I'll admit that since creating this theme, I've learned more about how to better organize CSS (Sass files specifically) and also learned a few lessons about dependencies.

I'd like to rewrite the theme's CSS (classes in the HTML files, and the Sass/CSS files themselves) to be more DRY, and independent of another framework (no Bulma). My preference would be to use Flexbox. 

I don't currently have the time to do this so I'm opening it up as an invitation to contribute. This is an issue best suited to someone with good working knowledge of CSS, Sass, and Flexbox.

The idea is to replicate the current design and two accompanying color versions (light and dark) with DRY code, using Flexbox. The CSS for each of the two color versions could easily be created using variables that can be changed in one Sass file.

**Comment by Hanzei** [comment]
Why do you want to move away from bulma?
