### ISSUE TITLE
Toc anchor link cannot be linked to the current page

### ISSUE THREAD

**Issue by Phoenix-Ann** [vickylai/hugo-theme-introduction#32]
Hi Vicky，I wanna the theme support toc，so I add Table of Contents by myself.Toc can display normally,but
toc anchor link cannot be linked to the current page.

### **Step：**
1.Open an article on my blog,ie [https://anna3.pub/blog/python3-with_python2/](https://anna3.pub/blog/python3-with_python2/)
2.Click on any section in toc,such as 
![default](https://user-images.githubusercontent.com/17487620/37394143-0e98ab48-27ae-11e8-97b9-e93e4233d5b3.png)

### **Result：**
Page jumps to https://anna3.pub/#python-launcher-for-windows

### **Expect:**
Page jumps to https://anna3.pub/python3-with_python2/#python-launcher-for-windows

I found  this is because  [ TableOfContents](https://gohugo.io/content-management/toc/#readout) call 
`<base href="{{ .Site.BaseURL }}">` which in /partials/header.html
So I comment out this line of code.Page junps to the correct page，but Css loading exception.
Like this

![tim 20180314175251](https://user-images.githubusercontent.com/17487620/37395162-8c9a8096-27b0-11e8-9342-e3542f3b552a.png)

## **Chrome reported the following error**
Refused to apply style from 'http://localhost:1313/blog/python3-with_python2/css/dark-style.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Looking forward to your reply!Thank you!

**Comment by hivickylai** [comment]
Hi @Phoenix-Ann. In your `config.toml` file, what do you have set for the `baseURL`?

**Comment by Hanzei** [comment]
This should be fixed now

**Comment by vickylai** [comment]
@Phoenix-Ann Can you try the latest theme and confirm?

**Comment by hanzei** [comment]
Closing this one for now. @Phoenix-Ann feel free to open it again if the issue still exists.

**Comment by Phoenix-Ann** [comment]
I have tried，it works with the latest theme. Thank you very much.
But there is another little bug,when content is English,it works.while content is Chinese it does't work.
