### ISSUE TITLE
Background scrolling on mobile phone

### ISSUE THREAD

**Issue by stueja** [vickylai/hugo-theme-introduction#46]
After opening a modal window e. g. after clicking on "Design", and scrolling the page up or down, the (nearly invisible) main page in the background is scrolling. After closing the modal by clicking the X in the upper right, the main page may be on a totally different position than before opening the modal.

**Comment by vickylai** [comment]
Apparently adding "overflow: hidden" to the body should prevent the scrolling when modal is open, but this doesn't seem to work...

**Comment by Hanzei** [comment]
```
body {
    overflow: hidden;
    position: fixed;
}
```
works fine. But we need to modify the css for this.

@vickylai Mind adding `package.json` and `gulpfile.js` to this repro, so I can compile the css myself?
