### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by Hanzei** [vickylai/hugo-theme-introduction#49]
A travis CI script could be used to make sure no wrong template could be added.

@vickylai If you enable travis, I would create a PR for this.

**Comment by Hanzei** [comment]
With Github Apps. If i am not mistaken, https://travis-ci.com/ is a Github App

**Comment by vickylai** [comment]
Found it. Enabled! Thanks @Hanzei for helping me experiment... :)

**Comment by Hanzei** [comment]
Travis is currently moving from travis-ci.org to travis-ci.com. (See https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com) I think you registered this rep on `.org`. Mind moving it over?

**Comment by vickylai** [comment]
Moved to .com. Thanks @Hanzei!
