### ISSUE TITLE
Remove enforce_ssl setting

### ISSUE THREAD

**Issue by Hanzei** [vickylai/hugo-theme-introduction#54]
Enforcing ssl/tls is nothing what should be done via js. A webserver should take care of this, not hugo. I propose to remove this option.

@vickylai Thoughts?

**Comment by vickylai** [comment]
Yes. Actually the thinking behind this is a little out of date. It was a hack I saw another theme use, long before I had tried Cloudflare then Let's Encrypt, and definitely before [GitHub Pages offered SSL](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) earlier this year. 

With all the (awesome) changes we've been making, I'd like to do a new release and also take a crack at making the Sass and different theme modes more DRY and forward-thinking (#29). Let's resolve this #54 in a branch and I'll include it in the new release, so as to not confuse anyone who might currently use the `enforce_ssl` setting.
