### ISSUE TITLE
Number of Projects showing variable?

### ISSUE THREAD

**Issue by Setherizor** [vickylai/hugo-theme-introduction#59]
Is there a way to create a new variable for the projects display called "numberToShow" or something similar to control the **number of projects to show on the main page**? 

It would be amazingly convenient if there was a way to **feature** a few projects then show the rest on the /projects page.

I personally would love to use this feature. :smile:

**Comment by Hanzei** [comment]
This should be not to hard to implement. We would also need a "show all projects" botton, which links to `/projects`
