### ISSUE TITLE
Configure about and contacts text without creating a new page

### ISSUE THREAD

**Issue by Hanzei** [vickylai/hugo-theme-introduction#63]
Currently to configure the about and contacts text, the user has to create a seperate page for both of them. But this also means that this pages are render with there own URL.

I propose to move `content/contact.md` text to a param and `content/about.md` to `content/index.md`. This would of course break backwards compatibility, but we could do this in a major release. I think, there will be no features lost.

**Comment by Hanzei** [comment]
A other possible solution is to us [headless bundles](https://gohugo.io/content-management/page-bundles/#headless-bundle)

**Comment by vickylai** [comment]
This will be addressed in the next major release. I'm currently keen on the headless option in addition to rendering the index page sections from markdown pages.

**Comment by Hanzei** [comment]
@vickylai If you are fine with the headless option I would go ahead and implement it.
I would add a headless section named `home/` and include `contact.md` and `footer.md`. The current `about.md` would go into `_index.md`.
