### ISSUE TITLE
Adding a background image

### ISSUE THREAD

**Issue by StevenPuttemans** [vickylai/hugo-theme-introduction#65]
Hi there and thanks for the theme, really enjoyed it so far!

I have custimized it a bit for a conference page we are building (https://stevenputtemans.github.io/AMV2018/). So far so good, but now I would love to have the first block, where the text spawns in, to contain a 50% opague background image.

I tried adding `style="background-image: url(../img/background.jpg)` to the `<div class="hero-body">` container, but that does not seem to do the trick. Any ideas on what I can try next?

**Comment by vickylai** [comment]
Hey Steven!

Site looks great. I love what you've done with it!

I tried `style="background-image: url(fullpath.jpg);background-size:cover;"` in the same `<div class="hero-body">` and it worked for me. You might need to check your path. Let me know if you still have an issue.

The 50% opaque part is possible if you add a pseudo element with 50% opacity, but if you're not comfortable doing that on your own I'd suggest that it would be easier to make the image itself 50% faded instead. That can be done in programs like GIMP or Photoshop, or with an online tool like Canva.

**Comment by StevenPuttemans** [comment]
Hi @vickylai , after breaking my head for hours it seems that I found the same solution as you suggested: https://stevenputtemans.github.io/AMV2018/ and it works flawlesly.

Will test with the opague now, but not sure if the site really needs it

**Comment by vickylai** [comment]
I think it looks fantastic. Well done!

**Comment by mingsu** [comment]
Hi @StevenPuttemans, really like your conference site, is that possible to share the code behind?

**Comment by StevenPuttemans** [comment]
Hi @mingsu you can basically find my original HUGO code at https://github.com/StevenPuttemans/own_website_hugo_code. Feel free to pick out any items you like! Still a lot of todo items on my list, but haven't found the time as post-doc to invest more.

**Comment by StevenPuttemans** [comment]
Ow you mean the conference website 🤦‍♂️ I will upload it tomorrow at work ...

**Comment by StevenPuttemans** [comment]
The code can be found at https://github.com/StevenPuttemans/amv_hugo_code
Had some issues with pc and forgot about this, but here you go! Feel free to reuse anything there.
