### ISSUE TITLE
Change Font Color 

### ISSUE THREAD

**Issue by patarol** [vickylai/hugo-theme-introduction#68]
Hi,

I'm creating a blog with your Hugo Theme and I love it.
I'm trying to change the icon colors in the `sass` file but setting the `$primary` color to a new one, but I can't do it.

I'm a `R/Python` programmer and I don't know how to program in `.css`. 
How can I accomplish it?

Thank you.

**Comment by vickylai** [comment]
Currently the sass file must first be compiled to css.

There's a new version of the theme in progress (#66) that will remove this requirement with the use of Hugo's new [Resource transformation functions](https://github.com/gohugoio/hugo/releases/tag/v0.43). Stay tuned! :)
