### ISSUE TITLE
Webpage is cutting off horizontally when inline code is too long

### ISSUE THREAD

**Issue by ericksnetwork** [vickylai/hugo-theme-introduction#72]
I'm having an error viewing my blog post on the Android Chrome Browser:
**If my syntax highlighting is too long then at a certain point the rest of the web page does not render. Please refer to below images.**

I've confirmed that it is definitely the syntax highlighting that is causing this with trial and error for every formatting that is present in the document. The only thing that triggers this rendering issue is when my inline code is too long.

For the sake of clarity here is the original blog:
https://ericksnetwork.github.io/blog/twitter/

Here is a copy of the same blog with each code entry being truncated at the end. 
https://ericksnetwork.github.io/blog/twitter---copy/

As you can see, truncating the code allows the web page to render completely. 

Here is a screenshot using my Android chrome browser. As you can see the text is there but it is not rendered. It can be highlighted but it cannot be seen. 
https://i.imgur.com/USaztsx.jpg

Here is another screenshot from my while viewing the page in "desktop mode". As you can see the text is there, and in this case, the text is being cut in half. 
https://i.imgur.com/uqNN7TX.jpg

Does anyone have any suggestions? 

Thanks!

**Comment by ericksnetwork** [comment]
Version: 
Hugo Static Site Generator v0.45.1 windows/amd64 BuildDate: 2018-07-25T08:56:57Z

Code: 
https://github.com/ericksnetwork/ericksnetwork.github.io

Thanks for looking into this Hanzei.

**Comment by Hanzei** [comment]
Sorry, I was a bit unclear. Could you share the source code of your website? I think the content of `content/blog/twitter---copy` and `content/blog/twitter` would be enough.

**Comment by ericksnetwork** [comment]
1 - [Twitter Copy]("https://github.com/ericksnetwork/ericksnetwork.github.io/blob/master/blog/twitter%20-%20Copy_source")

2 - [Twitter]("https://github.com/ericksnetwork/ericksnetwork.github.io/blob/master/blog/twitter_source")

**Comment by Hanzei** [comment]
Thanks for the code. Unfortunately I was not able to reproduce your issue neither with a local compiled version nor with your page under https://ericksnetwork.github.io/blog/twitter/.

Did you try to access you page with another browser? Can you reproduce your issue at a desktop computer, if you alter the screen size?

**Comment by ericksnetwork** [comment]
I've tested this issue on 4 different peoples phones which were all Android. Unfortunately the page does not render properly. 

I also just downloaded the Brave browser and Opera to test out this issue. The issue persists across these browsers. Here are some more screenshots. 

![screenshot_20180810-022202](https://user-images.githubusercontent.com/8908857/43942049-81b4d65a-9c44-11e8-9d09-f62f425ec89a.jpg)

![screenshot_20180810-022329](https://user-images.githubusercontent.com/8908857/43942050-81c4f21a-9c44-11e8-9051-16e43878f640.jpg)

It must have to do with the size of the screen then. How would you suggest I test different screen sizes on my computer?

**Comment by Hanzei** [comment]
I was able to reproduce your issue. It only occurs on a android smartphone with a chromium based browser, like google chrome or opera. It works fine with Firefox for me.

This is rather strange. I will look into this more in a week, because I'm on vacation next week. It will be hard to debug on a smartphone, but I will give it a try.

> It must have to do with the size of the screen then. How would you suggest I test different screen sizes on my computer?

See https://developers.google.com/web/tools/chrome-devtools/device-mode/

**Comment by ericksnetwork** [comment]
Thanks Hanzei! I'll keep doing some research on my end to see what this may be. 

Again - I'm no web dev so my JS is limited but I did run across a few stackoverflow threads that might be related? 

1. https://stackoverflow.com/questions/51758881/webpage-is-cutting-off-horizontally-in-mobile-version/51764385#51764385
2. https://stackoverflow.com/questions/31208959/inline-block-ul-with-opacity-causes-end-to-cut-off
3. https://stackoverflow.com/questions/10143481/div-gets-cut-off-even-though-width-and-height-are-defined
4. https://stackoverflow.com/questions/18222409/specifying-a-preferred-line-break-point-in-html-text-in-a-responsive-design

**Comment by ericksnetwork** [comment]
Hi guys - any update on this?

**Comment by Hanzei** [comment]
Would you try upgrading to the latest version of this theme? A lot changed with the latest update. It might fix your problem.

**Comment by ericksnetwork** [comment]
Thanks for following up. 

I downloaded the latest version of [https://github.com/gohugoio/hugo/releases/tag/v0.48](hugo_0.48_Windows-64bit.zip)

**Comment by Hanzei** [comment]
> Do I have to install PostCSS on my side?

Yes

**Comment by ericksnetwork** [comment]
I finally got around to implementing the new versions and am happy to say that the issue on chromium browsers seems to have been fixed.

Thanks for all your help!

**Comment by Hanzei** [comment]
The is no option to set the nav bar centred. But you can use https://github.com/vickylai/hugo-theme-introduction#custom-css to do this.

**Comment by joewaj** [comment]
At the moment I am also trying to center the nav bar and I am not a CSS guru (more familiar with C/C++). Some attempts with custom-css doesn't work (although I already managed to add some other modifications to the theme successfully). Maybe you can give some hints which elements and properties should be modified.
Anyway, thank you for your very nice work on introduction!!

**Comment by Hanzei** [comment]
See #88
