### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by r33int** [vickylai/hugo-theme-introduction#73]
Hello, I have tried running this theme on Hugo v0.46. However, I am facing this error when I try to run the hugo server: 
```
Building sites … ERROR 2018/08/13 18:38:32 Error while rendering "home" in "": template: index.html:77:11: executing "index.html" at <partial "projects.ht...>: error calling partial: template: partials/projects.html:7:63: executing "partials/projects.html" at <"projects">: can't evaluate field Pages in type *hugolib.Page
Total in 11 ms
Error: Error building site: logged 1 error(s)
```

Here is what hugo version returns:
``
Hugo Static Site Generator v0.46 linux/amd64 BuildDate: 2018-08-01T09:00:55Z
``

**Comment by Hanzei** [comment]
Thanks for you report @r33int.

Do you want to show a projects section? If no, try setting `showProjects` in `config.toml` to `false. If yes, you need to create pages under `content/projects`.

**Comment by r33int** [comment]
I added a page under projects and it worked! I didn't know it was necessarry to create a page to get it working. Thanks!
