### ISSUE TITLE
Assets not loading when root domain includes path?

### ISSUE THREAD

**Issue by vickylai** [vickylai/hugo-theme-introduction#85]
I've set up `docs/` as the demo site, generated from the `exampleSite/` folder with:

```
hugo --themesDir ../.. -d ../docs 
```

It seems that no assets load at https://vickylai.com/hugo-theme-introduction/ unless (as a bandaid solution) I also include:

```
--baseURL https://vickylai.com/hugo-theme-introduction/
```

In which case the css loads, but none of the fonts.

Is this related to `assets/sass/style.sass` font paths?

**Comment by Hanzei** [comment]
I will look into this.

**Comment by Hanzei** [comment]
Running ` hugo --themesDir ../.. -d ../docs  -v  -b https://vickylai.com/hugo-theme-introduction/` works fine for me. Are you sure that you use the current `master`?

BTW: Why do you commited `docs/` to this repo? We kind of already have a example with `examplesite/`  and https://themes.gohugo.io/theme/hugo-theme-introduction/.

**Comment by Hanzei** [comment]
Seams like https://themes.gohugo.io/theme/hugo-theme-introduction/ has the same problem. But i still cant reproduce it locally.

**Comment by vickylai** [comment]
@Hanzei `docs/` replaces an example site previously stored in another repository, and serves the GitHub Pages site for this repo.

https://themes.gohugo.io/theme/hugo-theme-introduction/ doesn't load any assets at all. The CSS url is `https://themes.gohugo.io/css/main.min.34f8ba287806e0ec83cbeb4f926ddfed78f3ab2453f7463ead739774a418747f.css` and is 404.

Does this issue have to do with SRI? (Is SRI really necessary here?)

**Comment by Hanzei** [comment]
> @Hanzei docs/ replaces an example site previously stored in another repository, and serves the GitHub Pages site for this repo.

ok, I see.

> Does this issue have to do with SRI? (Is SRI really necessary here?)

I'm pretty doesn't have to do with SRI. The problem is that the files don't get found, not that they are rejected.

> https://themes.gohugo.io/theme/hugo-theme-introduction/ doesn't load any assets at all. The CSS url is https://themes.gohugo.io/css/main.min.34f8ba287806e0ec83cbeb4f926ddfed78f3ab2453f7463ead739774a418747f.css and is 404.

What confuses me is that we don't construct the URL by our self. See https://github.com/vickylai/hugo-theme-introduction/blob/master/layouts/partials/head/css.html#L11
This might be a hugo problem. I will look into it.

>Running hugo --themesDir ../.. -d ../docs -v -b https://vickylai.com/hugo-theme-introduction/ works fine for me. Are you sure that you use the current master?

Did this fix your problem?

**Comment by vickylai** [comment]
> Did this fix your problem?

Same result as I first mentioned, where the CSS and other assets load, but not FontAwesome.

**Comment by Hanzei** [comment]
@vickylai What hugo version are you using?

**Comment by vickylai** [comment]
`Hugo Static Site Generator v0.48/extended linux/amd64 BuildDate: 2018-08-29T06:57:35Z`

**Comment by hanzei** [comment]
I create a build script for the docs. Could you checkout the branch `docs_script` and run `./scripts/build_docs.sh`. I hope this solves your problem.

**Comment by vickylai** [comment]
The script is just...?

```
cd exampleSite
hugo --gc --minify --themesDir ../.. -d ../docs -v -b https://vickylai.com/hugo-theme-introduction/
```

I've rebuilt the docs site but the result is the same. The assets load fine all except for fontawesome.

I think there is still an underlying issue here, given that https://themes.gohugo.io/theme/hugo-theme-introduction/ does not load any assets. The script only attempts to address building docs/.

**Comment by vickylai** [comment]
Despite merging #96, the font awesome issue seems to persist on https://vickylai.com/hugo-theme-introduction/

**Comment by hanzei** [comment]
For further discussion about the bug on https://themes.gohugo.io/theme/hugo-theme-introduction/ see #106
