### ISSUE TITLE
Nav bar is not centered

### ISSUE THREAD

**Issue by joewaj** [vickylai/hugo-theme-introduction#88]
The navigation bar seems to be left aligned.  It would be nice to have it centerd or to have a switch to do this in config.toml (especially when you have few nav bar entries). I already tried to fix this with custom.css but without success.
A hint which elements and properties are needed here in custom.css would be also helpful for me.
Thanks!

**Comment by Hanzei** [comment]
Adding 
```css
.navbar-item {
    flex: auto;
}
```
Should help

**Comment by joewaj** [comment]
Thanx. Works fine for me

**Comment by ericksnetwork** [comment]
> Thanx. Works fine for me

joewaj - can i ask what exactly you did to get the nav bar center aligned? I'm not exactly sure how and where to place the snippet provided by hanzei.

**Comment by joewaj** [comment]
1. I created an extra file "custom.css" at the "assets" folder of the theme and copy/pasted the 3 lines into that file
2. You have to add this file name at config.toml (Entry: customCSS= ["custom.css"])

The entries from custom.css  will overwrite the the original css properties of the theme.
For fine tuning the theme I use the firefox built-in inspector to find out which items and properties to modify. You can add and modify properties on-the-fly with inspector. (For example try to add "flex: auto;"  at Demo page of "introduction" (https://themes.gohugo.io/theme/hugo-theme-introduction/) but it doesn't seem to work correctly at the moment.
