### ISSUE TITLE
error calling Concat: slice []interface {} not supported in concat

### ISSUE THREAD

**Issue by andreas-h** [vickylai/hugo-theme-introduction#92]
I'm using Hugo 0.49 and cannot use this theme.  When trying to compile, e.g., following the instructions in https://github.com/vickylai/hugo-theme-introduction#preview-the-theme, I get the error

    Building sites … ERROR 2018/10/03 17:29:01 Error while rendering "page" in "projects/design/": template: projects/single.html:36:11: executing "js-include" at <partial "footer/scri...>: error calling partial: template: partials/footer/scripts.html:3:47: executing "partials/footer/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
    ERROR 2018/10/03 17:29:01 Error while rendering "page" in "blog/": template: blog/single.html:36:11: executing "js-include" at <partial "footer/scri...>: error calling partial: template: partials/footer/scripts.html:3:47: executing "partials/footer/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
    ERROR 2018/10/03 17:29:01 Error while rendering "page" in "projects/photography/": template: projects/single.html:36:11: executing "js-include" at <partial "footer/scri...>: error calling partial: template: partials/footer/scripts.html:3:47: executing "partials/footer/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
    ERROR 2018/10/03 17:29:01 Error while rendering "page" in "projects/writing/": template: projects/single.html:36:11: executing "js-include" at <partial "footer/scri...>: error calling partial: template: partials/footer/scripts.html:3:47: executing "partials/footer/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
    ERROR 2018/10/03 17:29:01 Error while rendering "taxonomy" in "": template: _default/taxonomy.html:36:11: executing "js-include" at <partial "footer/scri...>: error calling partial: template: partials/footer/scripts.html:3:47: executing "partials/footer/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
    ERROR 2018/10/03 17:29:01 Error while rendering "section" in "blog/": template: blog/list.html:36:11: executing "js-include" at <partial "footer/scri...>: error calling partial: template: partials/footer/scripts.html:3:47: executing "partials/footer/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
    ERROR 2018/10/03 17:29:01 Error while rendering "taxonomyTerm" in "": template: _default/terms.html:36:11: executing "js-include" at <partial "footer/scri...>: error calling partial: template: partials/footer/scripts.html:3:47: executing "partials/footer/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
    ERROR 2018/10/03 17:29:01 Error while rendering "home" in "": template: index.html:108:11: executing "index.html" at <partial "footer/scri...>: error calling partial: template: partials/footer/scripts.html:3:47: executing "partials/footer/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
    ERROR 2018/10/03 17:29:01 Error while rendering "section" in "projects/": template: projects/list.html:36:11: executing "js-include" at <partial "footer/scri...>: error calling partial: template: partials/footer/scripts.html:3:47: executing "partials/footer/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
    ERROR 2018/10/03 17:29:01 Error while rendering "404" in "": template: 404.html:36:11: executing "js-include" at <partial "footer/scri...>: error calling partial: template: partials/footer/scripts.html:3:47: executing "partials/footer/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
    Total in 563 ms
    Error: Error building site: logged 10 error(s)

I also tried the [`hugo_49` branch,](https://github.com/vickylai/hugo-theme-introduction/tree/hugo_49) but the errors are the same.

Am I missing something?

**Comment by hanzei** [comment]
Dublicate of #91
